[[inputs.modbus]]
 alias = "Satec PM335"
 interval = "5s"
 name_override="Satec"
 tagexclude = ["type", "name", "host"]
 name = "NOT USED"
 slave_id = 1
 timeout = "3s"
 controller = "tcp://127.0.0.1:502"
 holding_registers = [	 
	 { name = "Ua",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.1,     address = [13312,13313]},	 	 
	 { name = "Ub",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.1,     address = [13314,13315]},	 	 
	 { name = "Uc",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.1,     address = [13316,13317]},	 	 
	 { name = "Ia",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.01,     address = [13318,13319]},	 	 
	 { name = "Ib",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.01,     address = [13320,13321]},	 	 
	 { name = "Ic",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.01,     address = [13322,13323]},	 	 
	 { name = "Uab",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.1,     address = [13372,13373]},	 	 
	 { name = "Ubc",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.1,     address = [13374,13375]},	 	 
	 { name = "Uac",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.1,     address = [13376,13377]},	 	 	 	 
	 { name = "P",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.001,     address = [13696,13697]},	 	 
	 { name = "Q",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.001,     address = [13698,13699]},
	 { name = "S",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.001,     address = [13700,13701]},	 	 
	 { name = "pF",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.001,     address = [13702,13703]},	 
	 { name = "I0",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.01,     address = [13826,13827]},	 	 	 
	 { name = "F",   byte_order = "CDAB",   data_type = "FIXED",   scale=0.01,     address = [13828,13829]},	 	 	 	      
]

[inputs.modbus.tags]
  plant = "My Plant"
  feeder = "Feeder 1"
